### ISSUE TITLE
Disable registration does not work in asp.net core angular template (with authentification)

### ISSUE THREAD

**Issue by 3im3r** [dotnet/AspNetCore.Docs.de-de#65]
In this template there is already a subset available, a new scaffold is not compatible with the existing code.

To disable the register comment out the link in _LoginPartial.cshtml:
@*
&lt;p&gt;
    &lt;a asp-page="./Register" asp-route-returnUrl="@Model.ReturnUrl"&gt;Register as a new user&lt;/a&gt;
&lt;/p&gt;
*@

And add endpoint redirections in code:
app.UseEndpoints(endpoints =&gt;
            {
                endpoints.MapGet("/Identity/Account/Register", context =&gt; Task.Factory.StartNew(() =&gt; context.Response.Redirect("/Identity/Account/Login", true, true)));
                endpoints.MapPost("/Identity/Account/Register", context =&gt; Task.Factory.StartNew(() =&gt; context.Response.Redirect("/Identity/Account/Login", true, true)));
            });

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 804e24dd-7e30-8cf5-2c99-1ffacb4582f6
* Version Independent ID: 3e25547b-e2c9-6634-2c38-2a77207f17d4
* Content: [Gerüst Identität in ASP.net Core Projekten](https://docs.microsoft.com/de-de/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-3.1&tabs=netcore-cli#feedback)
* Content Source: [aspnetcore/security/authentication/scaffold-identity.md](https://github.com/dotnet/AspNetCore.Docs.de-de/blob/live/aspnetcore/security/authentication/scaffold-identity.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by srvbpigh** [comment]
Hello, @3im3r
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
Hello, @3im3r, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/dotnet/AspNetCore.Docs/issues/18029. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
