### ISSUE TITLE
Missing Docs for "Blazor Server"

### ISSUE THREAD

**Issue by XmlmXmlmX** [dotnet/AspNetCore.Docs.de-de#66]
The Link is present, but refers to "https://docs.microsoft.com/de-de/?view=aspnetcore-3.1"?

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: c9942b0a-a7fb-0d34-9201-af0963affa9e
* Version Independent ID: 19770710-5225-a1ea-e082-65da6ba4a49a
* Content: [Authentifizierung und Autorisierung in ASP.NET Core Blazor](https://docs.microsoft.com/de-de/aspnet/core/security/blazor/?view=aspnetcore-3.1)
* Content Source: [aspnetcore/security/blazor/index.md](https://github.com/dotnet/AspNetCore.Docs.de-de/blob/live/aspnetcore/security/blazor/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
It's not ideal, but you can look at the English docs until the localized docs are available ...

https://docs.microsoft.com/en-us/aspnet/core/security/blazor/server/

**Comment by srvbpigh** [comment]
Hello, @XmlmXmlmX
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hi @XmlmXmlmX 
Thank you for your feedback.
What @guardrex said is correct, the delay in the localized version is within the expected and will be available after the next translation round.

Kind regards,
Microsoft DOCS International Team

**Comment by XmlmXmlmX** [comment]
> It's not ideal, but you can look at the English docs until the localized docs are available ...
> 
> https://docs.microsoft.com/en-us/aspnet/core/security/blazor/server/

English is ok for me :)
