### ISSUE TITLE
NavLink Component renders no rel attribute

### ISSUE THREAD

**Issue by XmlmXmlmX** [dotnet/AspNetCore.Docs.de-de#68]
In section [NavLink Component](https://docs.microsoft.com/de-de/aspnet/core/blazor/fundamentals/routing?view=aspnetcore-3.1#navlink-component) the renderd output example is different to my result.

The documentation says:

```
<NavLink href="my-page" target="_blank">My page</NavLink>
```

should render this:

```
<a href="my-page" target="_blank" rel="noopener noreferrer">My page</a>
```

For me no `rel`-Attribute is rendered. But would be nice in combination with `target="_blank"` 😄.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 35474d24-8039-f04a-de14-1530b8e8506c
* Version Independent ID: b6cb2574-6326-a40d-0b6c-d1661328e828
* Content: [ASP.NET Core Blazor-Routing](https://docs.microsoft.com/de-de/aspnet/core/blazor/fundamentals/routing?view=aspnetcore-3.1)
* Content Source: [aspnetcore/blazor/fundamentals/routing.md](https://github.com/dotnet/AspNetCore.Docs.de-de/blob/live/aspnetcore/blazor/fundamentals/routing.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by srvbpigh** [comment]
Hallo @XmlmXmlmX:

Wir überarbeiten derzeit unseren internen Prozess und die Engineeringpipeline. Das führt leider zu Verzögerungen bei der Verarbeitung Ihres Feedbacks.

Vielen Dank für Ihren Beitrag zu unseren Artikeln und Ihr Verständnis. Wir freuen uns auf Ihre weitere Unterstützung.

**Comment by Rick-Anderson** [comment]
Please transfer this issue to https://github.com/dotnet/AspNetCore.Docs/issues

**Comment by guardrex** [comment]
@Rick-Anderson ... This one can be closed. It was addressed back in July on https://github.com/dotnet/AspNetCore.Docs/pull/19041.

**Comment by Rick-Anderson** [comment]
Please close as this is fixed.
