### ISSUE TITLE
Wrong translation of case-insensitive

### ISSUE THREAD

**Issue by lukoerfer** [dotnet/AspNetCore.Docs.de-de#72]
The section *Configuration keys and values* of the article *Configuration in ASP.NET Core* says:

> Configuration keys: [...] Are case-insensitive

However, in the German translation it says:

> Groß-/Kleinschreibung wird beachtet.

This would actually mean the configuration keys are case-sensitive, because it literally translates to something like:

> Upper / lower case is taken into account.

Possible fixes would be the following sentences:

> Groß-/Kleinschreibung wird nicht beachtet.
> Groß-/Kleinschreibung wird ignoriert.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 0eb4d762-3910-2c57-8741-3306c15537b6
* Version Independent ID: ba2254a0-ea8e-9b28-e94b-edd0fc58c043
* Content: [Konfiguration in ASP.NET Core](https://docs.microsoft.com/de-de/aspnet/core/fundamentals/configuration/?view=aspnetcore-3.1)
* Content Source: [aspnetcore/fundamentals/configuration/index.md](https://github.com/dotnet/AspNetCore.Docs.de-de/blob/live/aspnetcore/fundamentals/configuration/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-fundamentals**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@JasonCard  this exact translation problem has come up before. Is there a solution. Rather than 

` case-insensitive` should we write `not case sensitive`? That might be easier to translate.

**Comment by JasonCard** [comment]
@Rick-Anderson Thank you for the suggestion. Yes, I agree we could probably eliminate this mistranslation if it said `not case-sensitive` instead of `case-insensitive`. If you could please help to update the source, then that would trigger re-translation of the fixed string.

**Comment by Rick-Anderson** [comment]
You can close this and I'll fix all occurrences of insensitive.
See https://github.com/dotnet/AspNetCore.Docs/issues/19636

**Comment by JasonCard** [comment]
Thank you, @Rick-Anderson !
And thank you @lukoerfer for catching and reporting this issue!

**Comment by Rick-Anderson** [comment]
@JasonCard  can you check to see if this can be fixed. It might be hard to enforce not using insensitive. In the mean time I'll replace it with `not sensitive.`

**Comment by JasonCard** [comment]
@Rick-Anderson Okay, I'll

**Comment by JasonCard** [comment]
@lukoerfer The translation is now fixed. Thank you very much for your feedback.

cc @Rick-Anderson
