### ISSUE TITLE
tutorial step Scaffold a controller not working with current VS

### ISSUE THREAD

**Issue by wandexer** [dotnet/AspNetCore.Docs.de-de#75]
The step: "Scaffold a controller" does not work as it gives an error (I installed VSStudio 2019 yesterday). This page mentions, that stepping back for .Design to v2.3.3 is required: https://developercommunity.visualstudio.com/content/problem/749192/problem-scaffolding-an-area-in-vs-2019-1.html
I would expect the tutorial working for a fresh installed VSStudio.
Thanks
Wilfried

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Tutorial: Erstellen einer Web-API mit ASP.NET Core](https://docs.microsoft.com/de-de/aspnet/core/tutorials/first-web-api?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/dotnet/AspNetCore.Docs.de-de/blob/live/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
The tutorial works, I'm not sure what you missed. 

> https://developercommunity.visualstudio.com/content/problem/749192/problem-scaffolding-an-area-in-vs-2019-1.html

That does not apply to the current SDK, version 3.1

Recommend closing this issue.

**Comment by wandexer** [comment]
Hi Rick,

thank you for the fast answer. 

This is actually the problem:

That does not apply to the current SDK, version 3.1

At the top of the tutorial it mentions.

Prerequisites

*	 <https://visualstudio.microsoft.com/downloads/?utm_medium=microsoft&utm_source=docs.microsoft.com&utm_campaign=inline+link&utm_content=download+vs2019> Visual Studio 2019 16.4 or later with the ASP.NET and web development workload
*	 <https://dotnet.microsoft.com/download/dotnet-core/3.1> .NET Core 3.1 SDK or later

So this is actually not correct, right?

Thank you,

Wilfried

 

Von: Rick Anderson <notifications@github.com> 
Gesendet: Freitag, 9. Oktober 2020 20:12
An: dotnet/AspNetCore.Docs.de-de <AspNetCore.Docs.de-de@noreply.github.com>
Cc: wandexer <wilfried.andexer@asapdigital.com>; Author <author@noreply.github.com>
Betreff: Re: [dotnet/AspNetCore.Docs.de-de] tutorial step Scaffold a controller not working with current VS (#75)

 

The tutorial works, I'm not sure what you missed.

https://developercommunity.visualstudio.com/content/problem/749192/problem-scaffolding-an-area-in-vs-2019-1.html

That does not apply to the current SDK, version 3.1

Recommend closing this issue.

**Comment by Rick-Anderson** [comment]
That's not correct. The current SDK works. There are problems with 2.2 and 3.0 versions, but not the current 3.1
Recommend closing this issue.

**Comment by wandexer** [comment]
Ok, was a misunderstanding. Works
