### ISSUE TITLE
How do you bind to conditional attributes?

### ISSUE THREAD

**Issue by taori** [dotnet/AspNetCore.Docs.de-de#77]
I am trying to conditionally have my element render like `<input disabled>` instead of `<input>` However i can't seem to find a way to do this. Is it possible?

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: b211df59-e1c9-86c0-c904-31fa3c361e6d
* Version Independent ID: 3f912dfc-5ba5-6c6c-ba93-1ae78508a5cc
* Content: [ASP.NET Core Blazor-Datenbindung](https://docs.microsoft.com/de-de/aspnet/core/blazor/components/data-binding?view=aspnetcore-3.1)
* Content Source: [aspnetcore/blazor/components/data-binding.md](https://github.com/dotnet/AspNetCore.Docs.de-de/blob/live/aspnetcore/blazor/components/data-binding.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@taori ...

```razor
<input disabled="@disabled" />

<button @onclick="ChangeInput">Enable/Disable Input</button>

@code {
    private bool disabled = true;

    private void ChangeInput()
    {
        disabled = !disabled;
    }
}
```

Note that issues for documentation must be opened on the English-US repo. When they're opened in another language (on this repo), they end up arriving to the localization team.

**Comment by taori** [comment]
Perhaps i should have been more indepth when asking the question but to be precise the issue seems related with this:

https://stackoverflow.com/questions/64418951/how-to-get-two-way-databindings-working-in-blazor

The databinding does not update based on the ChildComponent using databind only without being the invoker of the event that prompts its values to change.

Ideally technically this issue gets documented in the databinding section too, because it was really confusing while attempting to solve it. If you delegate property values as pointed out in the post what i am trying to do starts working no problem. But using just one property as parameter and binding property makes it behave really weird.

**Comment by guardrex** [comment]
I don't have a large amount of time to study that post ... I'm 🏃😅 on a lot of .NET 5.0 work for the upcoming release, but we've already documented components not writing to their own parameters if that's what this is about ...

https://docs.microsoft.com/aspnet/core/blazor/components/?view=aspnetcore-3.1#overwritten-parameters

**Comment by guardrex** [comment]
There's also an example at ...

https://docs.microsoft.com/aspnet/core/blazor/components/data-binding#bind-across-more-than-two-components

**Comment by taori** [comment]
Essentially the key link in the reference is to [this](https://github.com/dotnet/aspnetcore/issues/24599#issuecomment-697588562)

Personally i will know in the future how my scenario is solved, but from orginally looking at the docs i was unable to find out how to fix it, because the docs to mention the overwriting parameters issue (especially your second link) but it doesn't jump at you. 

Hard to tell how to proceed with this, especially if you are more busy with other things right now

**Comment by guardrex** [comment]
I'll open an issue to take a look when we're out past .NET 5's release a bit. What you linked is probably Steve's best explanation of what's going on.

I'll see how I can surface the problem in the docs and improve the existing content.

When I open the new issue on our repo (the English-US one), you can close this issue here. I'll cross-link to this and to Steve's remarks. I'll ping u on it.

**Comment by taori** [comment]
Okay cool thanks. I just wanted to make sure that this is documented in a way where it can easily be taken note of, because technically it makes sense it has to be solved like this, but if someone did a prototype for a project they may run into the same issue and discard blazor because of it, which is sad, because blazor is like the first time where i actually enjoyed the workflow of writing a web application for a long time. 

Anyways. Enough with the ramble. once you add the issue+reference i will close this one.
