### ISSUE TITLE
Error with the word "Blazor"

### ISSUE THREAD

**Issue by pavll** [dotnet/AspNetCore.Docs.de-de#78]
[Hier Feedback eingeben]
One this site there is very often this: `:::no-loc(Blazor):::` on places where this should stand: `Blazor`
I think this is an error!

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: be59faf1-5a20-b7e9-19ff-06589023bb15
* Version Independent ID: 250e7458-3c1d-0117-261d-c03ac136f16a
* Content: [Hosten und Bereitstellen von ASP.NET Core :::no-loc(Blazor WebAssembly):::](https://docs.microsoft.com/de-de/aspnet/core/blazor/host-and-deploy/webassembly?view=aspnetcore-3.1#hosted-deployment-with-multiple-no-locblazor-webassembly-apps)
* Content Source: [aspnetcore/blazor/host-and-deploy/webassembly.md](https://github.com/dotnet/AspNetCore.Docs.de-de/blob/live/aspnetcore/blazor/host-and-deploy/webassembly.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @pavll ... I recommend that you close this issue and re-open it from the **English-US** site:

https://docs.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly?view=aspnetcore-3.1#feedback

**Comment by guardrex** [comment]
@pavll ... Just found out today. That's a known issue. They're working on it. See the remark at :point_right: https://github.com/dotnet/AspNetCore.Docs/pull/20366#issuecomment-719736540

**Comment by pavll** [comment]
Nice to hear that they're working on it. So I will close this issue.
