### ISSUE TITLE
:::no-loc(Identity):::  hier hat ein Skript wohl die Parameter nicht ersetzt. 

### ISSUE THREAD

**Issue by Otto404** [dotnet/AspNetCore.Docs.de-de#79]
:::no-loc(Identity):::  ist (wahrscheinlich) eine Variable, die ersetzt werden sollte. Die (ungefähre) Bedeutung kann zwar vom Kontext abgeleitet werden, aber in dieser rohen Form ist das Lesen doch arg erschwert. 
In der englischen Form /en-us/ ist der Text ohne Beanstandungen. 

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: db6772c4-1017-5e86-8045-8849b5dd1ad7
* Version Independent ID: bcb8d6b2-f38a-ac10-d3f2-69d4223bfd72
* Content: [Migrieren von Authentifizierung und :::no-loc(Identity)::: zu ASP.net Core](https://docs.microsoft.com/de-de/aspnet/core/migration/identity?view=aspnetcore-3.1)
* Content Source: [aspnetcore/migration/identity.md](https://github.com/dotnet/AspNetCore.Docs.de-de/blob/live/aspnetcore/migration/identity.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-migration**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
@Otto404  I think this has been fixed. If so, can you close the issue?

**Comment by Otto404** [comment]
:)
