### ISSUE TITLE
Error in example

### ISSUE THREAD

**Issue by tomschrot** [dotnet/AspNetCore.Docs.de-de#83]
The line 

var content = response.Content.ReadFromJsonAsync<WeatherForecast>();

should be 

var content = await response.Content.ReadFromJsonAsync<WeatherForecast>();

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 8b5e2e10-ff7b-2b9f-84da-f16028ae2c53
* Version Independent ID: c7e59a08-1c60-32c2-75fd-33cb77ff7a5d
* Content: [Aufrufen einer Web-API über ASP.NET Core Blazor WebAssembly](https://docs.microsoft.com/de-de/aspnet/core/blazor/call-web-api?view=aspnetcore-5.0)
* Content Source: [aspnetcore/blazor/call-web-api.md](https://github.com/dotnet/AspNetCore.Docs.de-de/blob/live/aspnetcore/blazor/call-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @tomschrot ... Could you close this and open it on the English-US repo (use the **This page** button at the bottom) at ...

https://docs.microsoft.com/en-us/aspnet/core/blazor/call-web-api?view=aspnetcore-5.0

**Comment by guardrex** [comment]
When an issue is opened on a localized version of the topic, it opens it for the localization team and doesn't make it to our repo where we work on the topics.

**Comment by Rick-Anderson** [comment]
@guardrex I have write permission now.
