### ISSUE TITLE
The nuget package for dbcontext is wrong

### ISSUE THREAD

**Issue by paule96** [dotnet/AspNetCore.Docs.de-de#86]
In the documentation is the nuget package `Microsoft.EntityFrameworkCore.SqlServer` required but never used.
Instead of that package the project uses `UseInMemoryDatabase` and this comes from `Microsoft.EntityFrameworkCore.InMemory`.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Tutorial: Erstellen einer Web-API mit ASP.NET Core](https://docs.microsoft.com/de-de/aspnet/core/tutorials/first-web-api?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/dotnet/AspNetCore.Docs.de-de/blob/live/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
This is correct. Please transfer this issue to https://github.com/dotnet/AspNetCore.Docs/issues and mention @Rick-Anderson

**Comment by Rick-Anderson** [comment]
Moved to https://github.com/dotnet/AspNetCore.Docs/issues/21411
Please close
