### ISSUE TITLE
The linked sample is nor more availabe 

### ISSUE THREAD

**Issue by DanielHWe** [dotnet/AspNetCore.Docs.de-de#89]
The linked sample is nor more availabe http 404

---
#### 

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 5ea474d5-234a-f393-8609-892a2deb5d2e
* Version Independent ID: c11d981c-05af-c19d-a333-feedd5978639
* Content: [ASP.NET Core Blazor-Dateiuploads](https://docs.microsoft.com/de-de/aspnet/core/blazor/file-uploads?view=aspnetcore-5.0)
* Content Source: [aspnetcore/blazor/file-uploads.md](https://github.com/dotnet/AspNetCore.Docs.de-de/blob/live/aspnetcore/blazor/file-uploads.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @DanielHWe ... Please close this issue and re-open it from the English-US `en-us` version of the topic. This issue can't be worked here because this is the localization repo.
